/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export type MEMOdbJS = MEMOdb
export class MEMOdb {
  constructor()
  createCollection(name: string): void
  getCollectionList(): Array<string>
  getCollection(name: string): Collection | null
}
export type CollectionJS = Collection
export class Collection {
  name: string
}
